fix Visual Studio 2015 "error C2059: syntax error: '::'"
This code wasn't touched since almost one year, suddenly the "std::max"
leads to syntax error at CI provider appveyor.

Signed-off-by: Martin <Ho-Ro@users.noreply.github.com>